// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Me defines model for Me.
type Me struct {
	Features        map[string]bool `json:"features"`
	IsCyodaEmployee bool            `json:"is_cyoda_employee"`
	OrgId           string          `json:"org_id"`
	Quota           struct {
		AppDeploys QuotaCounter `json:"app_deploys"`
		EnvDeploys QuotaCounter `json:"env_deploys"`
	} `json:"quota"`
	Roles  []string `json:"roles"`
	Scopes []string `json:"scopes"`
	Tier   string   `json:"tier"`
	UserId string   `json:"user_id"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// QuotaCounter defines model for QuotaCounter.
type QuotaCounter struct {
	Limit  int    `json:"limit"`
	Used   int    `json:"used"`
	Window string `json:"window"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV2WellKnownCliMinVersion request
	GetV2WellKnownCliMinVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2WellKnownOpenapiJson request
	GetV2WellKnownOpenapiJson(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2Me request
	GetV2Me(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV2WellKnownCliMinVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2WellKnownCliMinVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV2WellKnownOpenapiJson(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2WellKnownOpenapiJsonRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV2Me(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2MeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV2WellKnownCliMinVersionRequest generates requests for GetV2WellKnownCliMinVersion
func NewGetV2WellKnownCliMinVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/.well-known/cli-min-version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV2WellKnownOpenapiJsonRequest generates requests for GetV2WellKnownOpenapiJson
func NewGetV2WellKnownOpenapiJsonRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/.well-known/openapi.json")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV2MeRequest generates requests for GetV2Me
func NewGetV2MeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV2WellKnownCliMinVersionWithResponse request
	GetV2WellKnownCliMinVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2WellKnownCliMinVersionResponse, error)

	// GetV2WellKnownOpenapiJsonWithResponse request
	GetV2WellKnownOpenapiJsonWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2WellKnownOpenapiJsonResponse, error)

	// GetV2MeWithResponse request
	GetV2MeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2MeResponse, error)
}

type GetV2WellKnownCliMinVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Min *string `json:"min,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetV2WellKnownCliMinVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV2WellKnownCliMinVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV2WellKnownOpenapiJsonResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetV2WellKnownOpenapiJsonResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV2WellKnownOpenapiJsonResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV2MeResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *Me
	ApplicationproblemJSON401 *Problem
}

// Status returns HTTPResponse.Status
func (r GetV2MeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV2MeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetV2WellKnownCliMinVersionWithResponse request returning *GetV2WellKnownCliMinVersionResponse
func (c *ClientWithResponses) GetV2WellKnownCliMinVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2WellKnownCliMinVersionResponse, error) {
	rsp, err := c.GetV2WellKnownCliMinVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2WellKnownCliMinVersionResponse(rsp)
}

// GetV2WellKnownOpenapiJsonWithResponse request returning *GetV2WellKnownOpenapiJsonResponse
func (c *ClientWithResponses) GetV2WellKnownOpenapiJsonWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2WellKnownOpenapiJsonResponse, error) {
	rsp, err := c.GetV2WellKnownOpenapiJson(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2WellKnownOpenapiJsonResponse(rsp)
}

// GetV2MeWithResponse request returning *GetV2MeResponse
func (c *ClientWithResponses) GetV2MeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2MeResponse, error) {
	rsp, err := c.GetV2Me(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2MeResponse(rsp)
}

// ParseGetV2WellKnownCliMinVersionResponse parses an HTTP response from a GetV2WellKnownCliMinVersionWithResponse call
func ParseGetV2WellKnownCliMinVersionResponse(rsp *http.Response) (*GetV2WellKnownCliMinVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV2WellKnownCliMinVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Min *string `json:"min,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetV2WellKnownOpenapiJsonResponse parses an HTTP response from a GetV2WellKnownOpenapiJsonWithResponse call
func ParseGetV2WellKnownOpenapiJsonResponse(rsp *http.Response) (*GetV2WellKnownOpenapiJsonResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV2WellKnownOpenapiJsonResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetV2MeResponse parses an HTTP response from a GetV2MeWithResponse call
func ParseGetV2MeResponse(rsp *http.Response) (*GetV2MeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV2MeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Me
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	}

	return response, nil
}
