// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for GetV2BuildsParamsAction.
const (
	GetV2BuildsParamsActionBuild  GetV2BuildsParamsAction = "build"
	GetV2BuildsParamsActionDeploy GetV2BuildsParamsAction = "deploy"
	GetV2BuildsParamsActionEnv    GetV2BuildsParamsAction = "env"
)

// Defines values for PostV2BuildsJSONBodyAction.
const (
	PostV2BuildsJSONBodyActionBuild  PostV2BuildsJSONBodyAction = "build"
	PostV2BuildsJSONBodyActionDeploy PostV2BuildsJSONBodyAction = "deploy"
)

// Build defines model for Build.
type Build struct {
	Action          *string    `json:"action,omitempty"`
	BuildId         string     `json:"build_id"`
	ChatId          *string    `json:"chat_id,omitempty"`
	CreatedAt       *time.Time `json:"created_at,omitempty"`
	JobStatus       *string    `json:"job_status,omitempty"`
	JobStatusText   *string    `json:"job_status_text,omitempty"`
	PipelineName    *string    `json:"pipeline_name,omitempty"`
	State           string     `json:"state"`
	TeamcityBuildId *string    `json:"teamcity_build_id,omitempty"`
}

// EnvAlreadyExistsProblem Returned when a non-terminal env with the same env_name already exists for the org.
type EnvAlreadyExistsProblem struct {
	Detail *string             `json:"detail,omitempty"`
	EnvId  *openapi_types.UUID `json:"env_id,omitempty"`
	Status *int                `json:"status,omitempty"`
	Title  *string             `json:"title,omitempty"`
	Type   *string             `json:"type,omitempty"`
}

// EnvDetail defines model for EnvDetail.
type EnvDetail struct {
	AppNamespace *string             `json:"app_namespace,omitempty"`
	BuildId      *string             `json:"build_id,omitempty"`
	CreationDate *time.Time          `json:"creation_date,omitempty"`
	CyodaEnvUrl  *string             `json:"cyoda_env_url,omitempty"`
	EnvId        *openapi_types.UUID `json:"env_id,omitempty"`

	// EnvName User-supplied env name. DNS-1123 label rules + reserved-name guards.
	// See spec §3 for full validation.
	EnvName     *EnvName `json:"env_name,omitempty"`
	M2mClientId *string  `json:"m2m_client_id,omitempty"`
	Namespace   *string  `json:"namespace,omitempty"`
	State       *string  `json:"state,omitempty"`
}

// EnvList defines model for EnvList.
type EnvList = []EnvSummary

// EnvName User-supplied env name. DNS-1123 label rules + reserved-name guards.
// See spec §3 for full validation.
type EnvName = string

// EnvSummary defines model for EnvSummary.
type EnvSummary struct {
	CreationDate *time.Time          `json:"creation_date,omitempty"`
	EnvId        *openapi_types.UUID `json:"env_id,omitempty"`

	// EnvName User-supplied env name. DNS-1123 label rules + reserved-name guards.
	// See spec §3 for full validation.
	EnvName   *EnvName `json:"env_name,omitempty"`
	Namespace *string  `json:"namespace,omitempty"`
	State     *string  `json:"state,omitempty"`
}

// Me defines model for Me.
type Me struct {
	Features        map[string]bool `json:"features"`
	IsCyodaEmployee bool            `json:"is_cyoda_employee"`
	OrgId           string          `json:"org_id"`
	Quota           struct {
		AppDeploys QuotaCounter `json:"app_deploys"`
		EnvDeploys QuotaCounter `json:"env_deploys"`
	} `json:"quota"`
	Roles  []string `json:"roles"`
	Scopes []string `json:"scopes"`
	Tier   string   `json:"tier"`
	UserId string   `json:"user_id"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// ProvisionRequest defines model for ProvisionRequest.
type ProvisionRequest struct {
	Backend string  `json:"backend"`
	ChatId  *string `json:"chat_id,omitempty"`

	// EnvName User-supplied env name. DNS-1123 label rules + reserved-name guards.
	// See spec §3 for full validation.
	EnvName EnvName `json:"env_name"`

	// M2mWithAdminRole Request that the bootstrap-minted M2M client also
	// receive the ADMIN role on the user's Cyoda env. Subject
	// to the env's `cyoda.security.web.jwt.m2m.admin-role-enabled`
	// feature flag — if disabled, the entity ends up in
	// Mint_Failed.
	M2mWithAdminRole *bool `json:"m2m_with_admin_role,omitempty"`
}

// QuotaCounter defines model for QuotaCounter.
type QuotaCounter struct {
	Limit  int    `json:"limit"`
	Used   int    `json:"used"`
	Window string `json:"window"`
}

// GetV2BuildsParams defines parameters for GetV2Builds.
type GetV2BuildsParams struct {
	Cursor *string                  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int                     `form:"limit,omitempty" json:"limit,omitempty"`
	Action *GetV2BuildsParamsAction `form:"action,omitempty" json:"action,omitempty"`
	State  *string                  `form:"state,omitempty" json:"state,omitempty"`
}

// GetV2BuildsParamsAction defines parameters for GetV2Builds.
type GetV2BuildsParamsAction string

// PostV2BuildsJSONBody defines parameters for PostV2Builds.
type PostV2BuildsJSONBody struct {
	Action         PostV2BuildsJSONBodyAction `json:"action"`
	BranchName     string                     `json:"branch_name"`
	ChatId         *string                    `json:"chat_id,omitempty"`
	InstallationId *string                    `json:"installation_id,omitempty"`
	IsPublic       *bool                      `json:"is_public,omitempty"`
	RepositoryUrl  string                     `json:"repository_url"`
}

// PostV2BuildsParams defines parameters for PostV2Builds.
type PostV2BuildsParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostV2BuildsJSONBodyAction defines parameters for PostV2Builds.
type PostV2BuildsJSONBodyAction string

// ListEnvsParams defines parameters for ListEnvs.
type ListEnvsParams struct {
	IncludeTerminal *bool `form:"include_terminal,omitempty" json:"include_terminal,omitempty"`
}

// ProvisionEnvParams defines parameters for ProvisionEnv.
type ProvisionEnvParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostV2BuildsJSONRequestBody defines body for PostV2Builds for application/json ContentType.
type PostV2BuildsJSONRequestBody PostV2BuildsJSONBody

// ProvisionEnvJSONRequestBody defines body for ProvisionEnv for application/json ContentType.
type ProvisionEnvJSONRequestBody = ProvisionRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV2WellKnownCliMinVersion request
	GetV2WellKnownCliMinVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2WellKnownOpenapiJson request
	GetV2WellKnownOpenapiJson(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2Builds request
	GetV2Builds(ctx context.Context, params *GetV2BuildsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV2BuildsWithBody request with any body
	PostV2BuildsWithBody(ctx context.Context, params *PostV2BuildsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV2Builds(ctx context.Context, params *PostV2BuildsParams, body PostV2BuildsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteV2BuildsBuildId request
	DeleteV2BuildsBuildId(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2BuildsBuildId request
	GetV2BuildsBuildId(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV2BuildsBuildIdCancel request
	PostV2BuildsBuildIdCancel(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListEnvs request
	ListEnvs(ctx context.Context, params *ListEnvsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProvisionEnvWithBody request with any body
	ProvisionEnvWithBody(ctx context.Context, params *ProvisionEnvParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ProvisionEnv(ctx context.Context, params *ProvisionEnvParams, body ProvisionEnvJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteEnv request
	DeleteEnv(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEnv request
	GetEnv(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelEnv request
	CancelEnv(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV2Me request
	GetV2Me(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV2WellKnownCliMinVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2WellKnownCliMinVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV2WellKnownOpenapiJson(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2WellKnownOpenapiJsonRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV2Builds(ctx context.Context, params *GetV2BuildsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2BuildsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV2BuildsWithBody(ctx context.Context, params *PostV2BuildsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV2BuildsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV2Builds(ctx context.Context, params *PostV2BuildsParams, body PostV2BuildsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV2BuildsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteV2BuildsBuildId(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteV2BuildsBuildIdRequest(c.Server, buildId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV2BuildsBuildId(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2BuildsBuildIdRequest(c.Server, buildId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV2BuildsBuildIdCancel(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV2BuildsBuildIdCancelRequest(c.Server, buildId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListEnvs(ctx context.Context, params *ListEnvsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEnvsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProvisionEnvWithBody(ctx context.Context, params *ProvisionEnvParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProvisionEnvRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProvisionEnv(ctx context.Context, params *ProvisionEnvParams, body ProvisionEnvJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProvisionEnvRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteEnv(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteEnvRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEnv(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEnvRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelEnv(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelEnvRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV2Me(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV2MeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV2WellKnownCliMinVersionRequest generates requests for GetV2WellKnownCliMinVersion
func NewGetV2WellKnownCliMinVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/.well-known/cli-min-version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV2WellKnownOpenapiJsonRequest generates requests for GetV2WellKnownOpenapiJson
func NewGetV2WellKnownOpenapiJsonRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/.well-known/openapi.json")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV2BuildsRequest generates requests for GetV2Builds
func NewGetV2BuildsRequest(server string, params *GetV2BuildsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/builds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cursor", runtime.ParamLocationQuery, *params.Cursor); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Action != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "action", runtime.ParamLocationQuery, *params.Action); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "state", runtime.ParamLocationQuery, *params.State); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV2BuildsRequest calls the generic PostV2Builds builder with application/json body
func NewPostV2BuildsRequest(server string, params *PostV2BuildsParams, body PostV2BuildsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV2BuildsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostV2BuildsRequestWithBody generates requests for PostV2Builds with any type of body
func NewPostV2BuildsRequestWithBody(server string, params *PostV2BuildsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/builds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Idempotency-Key", runtime.ParamLocationHeader, params.IdempotencyKey)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

	}

	return req, nil
}

// NewDeleteV2BuildsBuildIdRequest generates requests for DeleteV2BuildsBuildId
func NewDeleteV2BuildsBuildIdRequest(server string, buildId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "build_id", runtime.ParamLocationPath, buildId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/builds/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV2BuildsBuildIdRequest generates requests for GetV2BuildsBuildId
func NewGetV2BuildsBuildIdRequest(server string, buildId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "build_id", runtime.ParamLocationPath, buildId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/builds/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV2BuildsBuildIdCancelRequest generates requests for PostV2BuildsBuildIdCancel
func NewPostV2BuildsBuildIdCancelRequest(server string, buildId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "build_id", runtime.ParamLocationPath, buildId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/builds/%s:cancel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListEnvsRequest generates requests for ListEnvs
func NewListEnvsRequest(server string, params *ListEnvsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/envs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.IncludeTerminal != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "include_terminal", runtime.ParamLocationQuery, *params.IncludeTerminal); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProvisionEnvRequest calls the generic ProvisionEnv builder with application/json body
func NewProvisionEnvRequest(server string, params *ProvisionEnvParams, body ProvisionEnvJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewProvisionEnvRequestWithBody(server, params, "application/json", bodyReader)
}

// NewProvisionEnvRequestWithBody generates requests for ProvisionEnv with any type of body
func NewProvisionEnvRequestWithBody(server string, params *ProvisionEnvParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/envs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Idempotency-Key", runtime.ParamLocationHeader, params.IdempotencyKey)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

	}

	return req, nil
}

// NewDeleteEnvRequest generates requests for DeleteEnv
func NewDeleteEnvRequest(server string, name EnvName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "name", runtime.ParamLocationPath, name)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/envs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEnvRequest generates requests for GetEnv
func NewGetEnvRequest(server string, name EnvName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "name", runtime.ParamLocationPath, name)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/envs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCancelEnvRequest generates requests for CancelEnv
func NewCancelEnvRequest(server string, name EnvName) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "name", runtime.ParamLocationPath, name)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/envs/%s:cancel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV2MeRequest generates requests for GetV2Me
func NewGetV2MeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV2WellKnownCliMinVersionWithResponse request
	GetV2WellKnownCliMinVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2WellKnownCliMinVersionResponse, error)

	// GetV2WellKnownOpenapiJsonWithResponse request
	GetV2WellKnownOpenapiJsonWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2WellKnownOpenapiJsonResponse, error)

	// GetV2BuildsWithResponse request
	GetV2BuildsWithResponse(ctx context.Context, params *GetV2BuildsParams, reqEditors ...RequestEditorFn) (*GetV2BuildsResponse, error)

	// PostV2BuildsWithBodyWithResponse request with any body
	PostV2BuildsWithBodyWithResponse(ctx context.Context, params *PostV2BuildsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV2BuildsResponse, error)

	PostV2BuildsWithResponse(ctx context.Context, params *PostV2BuildsParams, body PostV2BuildsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV2BuildsResponse, error)

	// DeleteV2BuildsBuildIdWithResponse request
	DeleteV2BuildsBuildIdWithResponse(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*DeleteV2BuildsBuildIdResponse, error)

	// GetV2BuildsBuildIdWithResponse request
	GetV2BuildsBuildIdWithResponse(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*GetV2BuildsBuildIdResponse, error)

	// PostV2BuildsBuildIdCancelWithResponse request
	PostV2BuildsBuildIdCancelWithResponse(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*PostV2BuildsBuildIdCancelResponse, error)

	// ListEnvsWithResponse request
	ListEnvsWithResponse(ctx context.Context, params *ListEnvsParams, reqEditors ...RequestEditorFn) (*ListEnvsResponse, error)

	// ProvisionEnvWithBodyWithResponse request with any body
	ProvisionEnvWithBodyWithResponse(ctx context.Context, params *ProvisionEnvParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProvisionEnvResponse, error)

	ProvisionEnvWithResponse(ctx context.Context, params *ProvisionEnvParams, body ProvisionEnvJSONRequestBody, reqEditors ...RequestEditorFn) (*ProvisionEnvResponse, error)

	// DeleteEnvWithResponse request
	DeleteEnvWithResponse(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*DeleteEnvResponse, error)

	// GetEnvWithResponse request
	GetEnvWithResponse(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*GetEnvResponse, error)

	// CancelEnvWithResponse request
	CancelEnvWithResponse(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*CancelEnvResponse, error)

	// GetV2MeWithResponse request
	GetV2MeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2MeResponse, error)
}

type GetV2WellKnownCliMinVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Min *string `json:"min,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetV2WellKnownCliMinVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV2WellKnownCliMinVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV2WellKnownOpenapiJsonResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetV2WellKnownOpenapiJsonResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV2WellKnownOpenapiJsonResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV2BuildsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Items      []Build `json:"items"`
		NextCursor *string `json:"next_cursor"`
	}
	ApplicationproblemJSON409 *Problem
}

// Status returns HTTPResponse.Status
func (r GetV2BuildsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV2BuildsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV2BuildsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *struct {
		BuildId *string `json:"build_id,omitempty"`
		State   *string `json:"state,omitempty"`
	}
	ApplicationproblemJSON403 *Problem
}

// Status returns HTTPResponse.Status
func (r PostV2BuildsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV2BuildsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteV2BuildsBuildIdResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON403 *Problem
}

// Status returns HTTPResponse.Status
func (r DeleteV2BuildsBuildIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteV2BuildsBuildIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV2BuildsBuildIdResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *Build
	ApplicationproblemJSON404 *Problem
}

// Status returns HTTPResponse.Status
func (r GetV2BuildsBuildIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV2BuildsBuildIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV2BuildsBuildIdCancelResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON403 *Problem
}

// Status returns HTTPResponse.Status
func (r PostV2BuildsBuildIdCancelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV2BuildsBuildIdCancelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListEnvsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EnvList
}

// Status returns HTTPResponse.Status
func (r ListEnvsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListEnvsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ProvisionEnvResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *EnvDetail
	JSON202                   *EnvDetail
	ApplicationproblemJSON400 *Problem
	ApplicationproblemJSON403 *Problem
	ApplicationproblemJSON409 *EnvAlreadyExistsProblem
	ApplicationproblemJSON429 *Problem
}

// Status returns HTTPResponse.Status
func (r ProvisionEnvResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProvisionEnvResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteEnvResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON404 *Problem
}

// Status returns HTTPResponse.Status
func (r DeleteEnvResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteEnvResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEnvResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *EnvDetail
	ApplicationproblemJSON404 *Problem
}

// Status returns HTTPResponse.Status
func (r GetEnvResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEnvResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CancelEnvResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON404 *Problem
	ApplicationproblemJSON409 *Problem
}

// Status returns HTTPResponse.Status
func (r CancelEnvResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelEnvResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV2MeResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *Me
	ApplicationproblemJSON401 *Problem
}

// Status returns HTTPResponse.Status
func (r GetV2MeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV2MeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetV2WellKnownCliMinVersionWithResponse request returning *GetV2WellKnownCliMinVersionResponse
func (c *ClientWithResponses) GetV2WellKnownCliMinVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2WellKnownCliMinVersionResponse, error) {
	rsp, err := c.GetV2WellKnownCliMinVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2WellKnownCliMinVersionResponse(rsp)
}

// GetV2WellKnownOpenapiJsonWithResponse request returning *GetV2WellKnownOpenapiJsonResponse
func (c *ClientWithResponses) GetV2WellKnownOpenapiJsonWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2WellKnownOpenapiJsonResponse, error) {
	rsp, err := c.GetV2WellKnownOpenapiJson(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2WellKnownOpenapiJsonResponse(rsp)
}

// GetV2BuildsWithResponse request returning *GetV2BuildsResponse
func (c *ClientWithResponses) GetV2BuildsWithResponse(ctx context.Context, params *GetV2BuildsParams, reqEditors ...RequestEditorFn) (*GetV2BuildsResponse, error) {
	rsp, err := c.GetV2Builds(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2BuildsResponse(rsp)
}

// PostV2BuildsWithBodyWithResponse request with arbitrary body returning *PostV2BuildsResponse
func (c *ClientWithResponses) PostV2BuildsWithBodyWithResponse(ctx context.Context, params *PostV2BuildsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV2BuildsResponse, error) {
	rsp, err := c.PostV2BuildsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV2BuildsResponse(rsp)
}

func (c *ClientWithResponses) PostV2BuildsWithResponse(ctx context.Context, params *PostV2BuildsParams, body PostV2BuildsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV2BuildsResponse, error) {
	rsp, err := c.PostV2Builds(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV2BuildsResponse(rsp)
}

// DeleteV2BuildsBuildIdWithResponse request returning *DeleteV2BuildsBuildIdResponse
func (c *ClientWithResponses) DeleteV2BuildsBuildIdWithResponse(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*DeleteV2BuildsBuildIdResponse, error) {
	rsp, err := c.DeleteV2BuildsBuildId(ctx, buildId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteV2BuildsBuildIdResponse(rsp)
}

// GetV2BuildsBuildIdWithResponse request returning *GetV2BuildsBuildIdResponse
func (c *ClientWithResponses) GetV2BuildsBuildIdWithResponse(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*GetV2BuildsBuildIdResponse, error) {
	rsp, err := c.GetV2BuildsBuildId(ctx, buildId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2BuildsBuildIdResponse(rsp)
}

// PostV2BuildsBuildIdCancelWithResponse request returning *PostV2BuildsBuildIdCancelResponse
func (c *ClientWithResponses) PostV2BuildsBuildIdCancelWithResponse(ctx context.Context, buildId string, reqEditors ...RequestEditorFn) (*PostV2BuildsBuildIdCancelResponse, error) {
	rsp, err := c.PostV2BuildsBuildIdCancel(ctx, buildId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV2BuildsBuildIdCancelResponse(rsp)
}

// ListEnvsWithResponse request returning *ListEnvsResponse
func (c *ClientWithResponses) ListEnvsWithResponse(ctx context.Context, params *ListEnvsParams, reqEditors ...RequestEditorFn) (*ListEnvsResponse, error) {
	rsp, err := c.ListEnvs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListEnvsResponse(rsp)
}

// ProvisionEnvWithBodyWithResponse request with arbitrary body returning *ProvisionEnvResponse
func (c *ClientWithResponses) ProvisionEnvWithBodyWithResponse(ctx context.Context, params *ProvisionEnvParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ProvisionEnvResponse, error) {
	rsp, err := c.ProvisionEnvWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProvisionEnvResponse(rsp)
}

func (c *ClientWithResponses) ProvisionEnvWithResponse(ctx context.Context, params *ProvisionEnvParams, body ProvisionEnvJSONRequestBody, reqEditors ...RequestEditorFn) (*ProvisionEnvResponse, error) {
	rsp, err := c.ProvisionEnv(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProvisionEnvResponse(rsp)
}

// DeleteEnvWithResponse request returning *DeleteEnvResponse
func (c *ClientWithResponses) DeleteEnvWithResponse(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*DeleteEnvResponse, error) {
	rsp, err := c.DeleteEnv(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteEnvResponse(rsp)
}

// GetEnvWithResponse request returning *GetEnvResponse
func (c *ClientWithResponses) GetEnvWithResponse(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*GetEnvResponse, error) {
	rsp, err := c.GetEnv(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEnvResponse(rsp)
}

// CancelEnvWithResponse request returning *CancelEnvResponse
func (c *ClientWithResponses) CancelEnvWithResponse(ctx context.Context, name EnvName, reqEditors ...RequestEditorFn) (*CancelEnvResponse, error) {
	rsp, err := c.CancelEnv(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelEnvResponse(rsp)
}

// GetV2MeWithResponse request returning *GetV2MeResponse
func (c *ClientWithResponses) GetV2MeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV2MeResponse, error) {
	rsp, err := c.GetV2Me(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV2MeResponse(rsp)
}

// ParseGetV2WellKnownCliMinVersionResponse parses an HTTP response from a GetV2WellKnownCliMinVersionWithResponse call
func ParseGetV2WellKnownCliMinVersionResponse(rsp *http.Response) (*GetV2WellKnownCliMinVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV2WellKnownCliMinVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Min *string `json:"min,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetV2WellKnownOpenapiJsonResponse parses an HTTP response from a GetV2WellKnownOpenapiJsonWithResponse call
func ParseGetV2WellKnownOpenapiJsonResponse(rsp *http.Response) (*GetV2WellKnownOpenapiJsonResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV2WellKnownOpenapiJsonResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetV2BuildsResponse parses an HTTP response from a GetV2BuildsWithResponse call
func ParseGetV2BuildsResponse(rsp *http.Response) (*GetV2BuildsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV2BuildsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Items      []Build `json:"items"`
			NextCursor *string `json:"next_cursor"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	}

	return response, nil
}

// ParsePostV2BuildsResponse parses an HTTP response from a PostV2BuildsWithResponse call
func ParsePostV2BuildsResponse(rsp *http.Response) (*PostV2BuildsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV2BuildsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest struct {
			BuildId *string `json:"build_id,omitempty"`
			State   *string `json:"state,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	}

	return response, nil
}

// ParseDeleteV2BuildsBuildIdResponse parses an HTTP response from a DeleteV2BuildsBuildIdWithResponse call
func ParseDeleteV2BuildsBuildIdResponse(rsp *http.Response) (*DeleteV2BuildsBuildIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteV2BuildsBuildIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	}

	return response, nil
}

// ParseGetV2BuildsBuildIdResponse parses an HTTP response from a GetV2BuildsBuildIdWithResponse call
func ParseGetV2BuildsBuildIdResponse(rsp *http.Response) (*GetV2BuildsBuildIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV2BuildsBuildIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Build
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	}

	return response, nil
}

// ParsePostV2BuildsBuildIdCancelResponse parses an HTTP response from a PostV2BuildsBuildIdCancelWithResponse call
func ParsePostV2BuildsBuildIdCancelResponse(rsp *http.Response) (*PostV2BuildsBuildIdCancelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV2BuildsBuildIdCancelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	}

	return response, nil
}

// ParseListEnvsResponse parses an HTTP response from a ListEnvsWithResponse call
func ParseListEnvsResponse(rsp *http.Response) (*ListEnvsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListEnvsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseProvisionEnvResponse parses an HTTP response from a ProvisionEnvWithResponse call
func ParseProvisionEnvResponse(rsp *http.Response) (*ProvisionEnvResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProvisionEnvResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest EnvDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest EnvAlreadyExistsProblem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	}

	return response, nil
}

// ParseDeleteEnvResponse parses an HTTP response from a DeleteEnvWithResponse call
func ParseDeleteEnvResponse(rsp *http.Response) (*DeleteEnvResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteEnvResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	}

	return response, nil
}

// ParseGetEnvResponse parses an HTTP response from a GetEnvWithResponse call
func ParseGetEnvResponse(rsp *http.Response) (*GetEnvResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEnvResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EnvDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	}

	return response, nil
}

// ParseCancelEnvResponse parses an HTTP response from a CancelEnvWithResponse call
func ParseCancelEnvResponse(rsp *http.Response) (*CancelEnvResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelEnvResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	}

	return response, nil
}

// ParseGetV2MeResponse parses an HTTP response from a GetV2MeWithResponse call
func ParseGetV2MeResponse(rsp *http.Response) (*GetV2MeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV2MeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Me
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	}

	return response, nil
}
